### ISSUE TITLE
Inline comments parsing problem

### ISSUE THREAD

**Issue by amkasprzyk** [GwynethLlewelyn/Go.novaextension#1]
Code such as:
---
//////////////////////////////////////////////////////////////////////
// Foo functions
//////////////////////////////////////////////////////////////////////

// foo bar cat.
func foo(s string) {
}
---
fails to render properly. (Inserting a space after the initial "//" on lines 1 and 3 fixes this.)

(Really great work -- thanks very much for taking the time to create this extension!)

**Comment by GwynethLlewelyn** [comment]
Yikes. Thanks for the heads-up. Now hopefully this is not beyond my ability to fix...

**Comment by GwynethLlewelyn** [comment]
Fixed on upcoming 0.4.0 release! (At last!)
