### ISSUE TITLE
Ranges of edits cannot be applied

### ISSUE THREAD

**Issue by wtfcxt** [GwynethLlewelyn/Go.novaextension#11]
Sometimes when I try to tab (for example `fmt.Println`) Nova shows me this error:
```
Ranges of edits cannot be applied to document "<path-to-go-file>", as they exceed the current content.
```
I censored the path but it would show the path of the file. Any ideas why this is happening? Also I noticed that sometimes the IntelliSense doesn't work at all and the only thing it suggests is `fmt.Fprint` (only tested fmt for now)

**Comment by GwynethLlewelyn** [comment]
Interesting... I have not encountered that error before!... then again, I might not have been actively searching for it...

 I've come across a few issues with IntelliSense myself, but not what you describe. I have to take a deeper look at this

**Comment by cxtwastaken** [comment]
It seems to be quite random, sometimes it works fine and sometimes it doesn't.

**Comment by GwynethLlewelyn** [comment]
Eek. I hate _those_ kinds of bugs! They're the trickiest to figure out...

**Comment by cxtwastaken** [comment]
<img width="381" alt="Bildschirmfoto 2021-04-27 um 16 01 00" src="https://user-images.githubusercontent.com/53837207/116254621-c8fb7d80-a771-11eb-90ce-5c96dfe6b924.png">
Now I can't even save files anymore lmao

Translation:
> The file "program.go" does not exist.

**Comment by jfieber** [comment]
That sure sounds like a case of Nova and gopls having divergent understandings of what is in the editor. If you encounter that, does closing the file (but not the workspace window) and re-opening it sort things out?

**Comment by cxtwastaken** [comment]
it doesn't always work

Am Mi., 28. Apr. 2021 um 00:28 Uhr schrieb John Fieber <
***@***.***>:

**Comment by GwynethLlewelyn** [comment]
Just for the record... since Nova 7.2 (at least, possibly as early as 7.0), I have never encountered these errors again. There _was_ a lot of refactoring done by Logan to better support LSP. At least as far as I'm concerned, it has fixed all the issues I used to have (including this one). @wtfcxt are you still having this issue? If not, can we close it?

**Comment by wtfcxt** [comment]
that's great! yeah we can close this issue
