### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by sgkul2000** [GwynethLlewelyn/Go.novaextension#4]
I'm unable to install the go extension on the panic nova editor. it takes forever to install and it shoes "<<Status>>" under the name of the extension while downloading. (not sure if this is the desired behavior)
It also shows an exclamatory mark in front of the extension name in the extensions list

**Comment by GwynethLlewelyn** [comment]
Ouch! I wish I knew how to help you...

**Comment by sgkul2000** [comment]
No problems, I manually downloaded and installed the extension at the time of the issue, But now it seems to be fixed in the latest version of nova.
